version: '3'
services:
  app:
    build: .
    ports: 
      - "8090:8090"
    environment: 
      - APP_HOST=8090
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=user
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      template:
        aliases:
          - mongo
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
    networks:
      template:
        aliases:
          - mongo-express
networks:
  template: {}
